//Doug Fultz
//Sujay Kallamadi
//CMPSC470 - Compiler Construction

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 30 12:46:41 EDT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 11;
  public static final int rw_WHILE = 35;
  public static final int rw_BOOL = 40;
  public static final int LBRACKET = 13;
  public static final int rw_IF = 34;
  public static final int SLASH = 25;
  public static final int rw_CONTINUE = 44;
  public static final int rw_FALSE = 46;
  public static final int LPAREN = 4;
  public static final int SEMI = 3;
  public static final int rw_PRINT = 41;
  public static final int rw_TRUE = 45;
  public static final int MINUS = 28;
  public static final int RPAREN = 5;
  public static final int NOT = 26;
  public static final int INTLIT = 10;
  public static final int rw_VOID = 31;
  public static final int LT = 17;
  public static final int rw_CONST = 33;
  public static final int COMMA = 6;
  public static final int INC = 29;
  public static final int rw_ELSE = 36;
  public static final int GEQ = 22;
  public static final int PLUS = 27;
  public static final int rw_READ = 37;
  public static final int rw_INT = 38;
  public static final int EOF = 0;
  public static final int RBRACKET = 14;
  public static final int error = 1;
  public static final int COR = 16;
  public static final int rw_CLASS = 32;
  public static final int rw_RETURN = 42;
  public static final int EQ = 19;
  public static final int ASG = 7;
  public static final int TIMES = 23;
  public static final int CHARLIT = 12;
  public static final int COLON = 24;
  public static final int LBRACE = 8;
  public static final int rw_CHAR = 39;
  public static final int RBRACE = 9;
  public static final int CAND = 15;
  public static final int LEQ = 21;
  public static final int rw_BREAK = 43;
  public static final int DEC = 30;
  public static final int GT = 18;
  public static final int NOTEQ = 20;
  public static final int IDENTIFIER = 2;
}

