//Doug Fultz
//Sujay Kallamadi
//CMPSC470 - Compiler Construction

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 30 12:46:41 EDT 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
    /* terminals */
    public static final int ASG = 7;
    public static final int CAND = 16;
    public static final int CHARLIT = 12;
    public static final int COLON = 25;
    public static final int COMMA = 6;
    public static final int COR = 17;
    public static final int DEC = 31;
    public static final int EOF = 0;
    public static final int EQ = 20;
    public static final int error = 1;
    public static final int FLOATLIT = 13;
    public static final int GEQ = 23;
    public static final int GT = 19;
    public static final int IDENTIFIER = 2;
    public static final int INC = 30;
    public static final int INTLIT = 10;
    public static final int LBRACE = 8;
    public static final int LBRACKET = 14;
    public static final int LEQ = 22;
    public static final int LPAREN = 4;
    public static final int LT = 18;
    public static final int MINUS = 29;
    public static final int NOT = 27;
    public static final int NOTEQ = 21;
    public static final int PLUS = 28;
    public static final int RBRACE = 9;
    public static final int RBRACKET = 15;
    public static final int RPAREN = 5;
    public static final int rw_BOOL = 43;
    public static final int rw_BREAK = 46;
    public static final int rw_CHAR = 42;
    public static final int rw_CLASS = 33;
    public static final int rw_CONST = 34;
    public static final int rw_CONTINUE = 47;
    public static final int rw_ELSE = 39;
    public static final int rw_FALSE = 49;
    public static final int rw_IF = 35;
    public static final int rw_INT = 41;
    public static final int rw_PRINT = 44;
    public static final int rw_READ = 40;
    public static final int rw_RETURN = 45;
    public static final int rw_TRUE = 48;
    public static final int rw_VOID = 32;
    public static final int rw_WHILE = 37;
    public static final int SEMI = 3;
    public static final int SLASH = 26;
    public static final int STRLIT = 11;
    public static final int TIMES = 24;
}

